---
title: "Reproduserbar og replikerbar forskning"
author: "Håkon Alne Paulsen og Hilde Kristin Jensen"
format:
  revealjs:
        theme: simple
        reveal_options:
        code-fold: show
        incremental: true
        smaller: true
        scrollable: true
        slide-number: c/t
editor: visual
editor_options:
  markdown:
    wrap: 72
    canonical: true
    chunk_output_type: console
echo: true
eval: true
bibliography: reproduserbarogreplikerbar.bib
nocite: '@*'
---

## Hva er reproduserbar

-   Gjenta en undersøkelse med samme data og prosedyrer å få samme
    resultat @halbo2023
-   Tilfeller der feil i analyseringen av data har ført til resultater
    som ikke stemmer
-   Minstekrav for at en artikkel skal kunne publiseres @peng2011

## Hva er replikerbar

-   Samme studie med andre data, men med samme konklusjon

-   Hvorfor er replikasjon viktig:

    -   sementere funn

    -   korrigere publikasjonsbias

    -   avsløre fusk og tvilsom forksningspraksis @svartdal2022

-   Hvorfor både reproduserbarhet og replikerbarhet

    -   feil i datasett - samme konklusjon ved reproduserbarhet

    -   feil i datasett - annen konklusjon ved replikerbarhet

-   Gullstandarden innenfor forskning @jasny2011

## Hvorfor er det viktig at forskning er reproduserbar og replikerbar

-   Vitenskap er bygget på tillit

-   ::: nonincremental
    Reproduserbar og replikerbar forskning minsker mulighet for feil i
    analysen og manipulering av data

    -   For eksempel forskning innen medisin @spilde2015
    :::

## Nåværende definisjon

-   National Science Foundation definerer robust og pålitelig vitenskap
    -   reproduserbart
    -   replikerbart
    -   generaliserbart
-   Grunnlaget for videre vitenskapelig utvikling

## Referanser
